version: "2.0"
services:
    mariadb:
        image: mariadb
        container_name: wesic-mariadb
        environment:
         - MYSQL_ROOT_USER=63a9f0ea7bb98050796b649e85481845 
         - MYSQL_ROOT_PASSWORD=a029d0df84eb5549c641e04a9ef389e5
        volumes:
         - .docker/mysql/:/var/lib/mysql
        ports:
         - 3306:3306
    php:
        build:
          context: .docker/
          dockerfile: Dockerfile
        volumes:
          - ./:/var/www/html/
          - .docker/php/apache2/apache2.conf:/etc/apache2/apache2.conf
        links:
         - mariadb:db
        ports:
          - "8080:80"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wesic-phpmyadmin
        environment:
         - MYSQL_ROOT_USER=63a9f0ea7bb98050796b649e85481845
         - MYSQL_ROOT_PASSWORD=a029d0df84eb5549c641e04a9ef389e5
        volumes:
         - .docker/phpmyadmin/fallen:/www/themes/fallen
         - .docker/phpmyadmin/conf.inc.php:/etc/phpmyadmin/conf.inc.php
        ports:
         - "8082:80"
        links:
         - mariadb:db
