config: 
    mysql:
      host: db
      dbuser: root 
      password: root
      dbname: wesic
    path:
      root: ""
      files: ""
    sitename: Wesic Inc.
    domain: "www.docker.local"
    debug: true