errors:
    email: Votre email n'est pas correct
    title: Votre titre n'est pas correct
    contentpage: Le contenu de la page doit faire plus de 10 caractères
    password: Votre mot de passe doit faire entre 8 et 12 caractères avec des chiffres, des majuscules et des minuscules
    login: Votre login marche braaaaaaaaaaah
    passwordconfirm: votre mot de passe de confirmation ne correspond pas
