errors:
    email: Votre email n'est pas correct
    title: Votre titre n'est pas correct
    contentpage: Le contenu de la page doit faire plus de 10 caractères
    password: Votre mot de passe doit faire entre 8 et 12 caractères avec des chiffres, des majuscules et des minuscules
    login: Votre login est incorrect
    passwordconfirm: votre mot de passe de confirmation ne correspond pas
    password2: votre mot de passe de confirmation ne correspond pas
    password1: votre mot de passe de confirmation ne correspond pas
    login404: votre login/mot de passe est incorrect
    userexists: le login/email existe déjà
    email-newsletter: Vous êtes déjà inscrit à la newsletter
    captcha: Le captcha est incorrect
    settings: Une erreur est survenue
    slogan: Slogan incorrect
    date: La date est incorrecte
    slug: Le permalien est existe
    content: Le corps de l'article est incorrect
    newlogin: votre login est incorrect
    role: le rôle est incorrect
    firstname: le prénom saisi est incorrect
    lastname: le nom saisi est incorrect
    edituser: une erreur s'est produite
    newcomment: une erreur s'est produite lors de l'ajout de votre commentaire
    tags: Les tags ne sont pas valides
    description: Vous devez saisir une description pour cet article
    excerpt: Vous devez saisir un extrait
    url-error: L'url est incorrecte
    media-name: Le nom du média saisi est incorrect
    file: Le fichier est invalide
    alttext: Le texte alternatif est incorrect
    legende: La légende est incorrecte
    