forms:
    publish:
        label: Publication
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true
    title:
        label: Titre
        container: col-md-12
        class: form-group
        aside: false
    content:
        label: Contenu
        container: col-md-12
        class: form-group
        aside: false
    excerpt:
        label: Résumé
        container: col-md-12
        class: form-group
        aside: false

    description:
        label: Description
        container: col-md-12
        class: form-group
        aside: false

    event:
        label:
        container: col-md-12
        class: form-group
        aside: false

    tags:
        label: Tags
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true    

    featured:
        label: Image mise en avant
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true

    category:
        label: Catégorie
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true

    edit-user-main:
        label:
        container: 
        class: 
        aside: false

    edit-user-actions:
        label: Actions avancées
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true

    title-settings:
        label: 
        container: col-md-12 form-group
        class: form-group
        aside: false
    url-settings:
        label:
        container: col-md-12 form-group
        class: form-group
        aside: false
    date-settings:
        label:
        container: col-md-12 form-group
        class: form-group
        aside: true
    publish-settings:
        label:
        container: col-md-12 form-group
        class: form-group
        aside: true

    attribute:
        label: Attributs de la page
        container: col-md-12 form-group form-group-alt-color
        class: form-group
        aside: true
