routing:

    Index:
        restricted: all
        controller: index:index
        path: ""

    Error:
        restricted: all
        controller: error:notFound
        path: error/index

    Error404:
        restricted: all
        controller: error:notFound
        path: error/404

    Error403:
        restricted: all
        controller: error:forbidden
        path: error/403

    Admin:
        restricted: admin
        controller: admin:index
        path: admin

    Logout:
        restricted: all
        controller: login:index
        path: login

    Login:
        restricted: all
        controller: login:logout
        path: logout

    Signup:
        restricted: all
        controller: login:signup
        path: newuser

    Update:
        restricted: all
        controller: login:update
        path: updateuser

    Profile:
        restricted: user
        controller: user:index
        path: profile

    NewArticle:
        restricted: all
        controller: cms:newArticle
        path: article/new

    NewCategory:
        restricted: all
        controller: cms:newCategory
        path: category/add
