routing:
    Index:
        restricted: all
        controller: index:index
        path: ""

    Error:
        restricted: all
        controller: error:notFound
        path: error

    Error404:
        restricted: all
        controller: error:notFound
        path: 404

    Error403:
        restricted: all
        controller: error:forbidden
        path: 403    

    Error500:
        restricted: all
        controller: error:down
        path: 500

    Admin:
        restricted: webmaster
        redirect: 
            guest: Login
            permission: Profile
        controller: admin:index
        path: admin

    Login:
        restricted: connected
        redirect: Admin
        controller: login:index
        path: connexion

    Logout:
        restricted: all
        redirect: Index
        controller: login:logout
        path: logout

    Signup:
        restricted: connected
        controller: login:signup
        path: inscription

    Profile:
        restricted: all
        controller: index:profil
        path: wesic/profil
        params:
            user:
                type: string
                optional: true

    NewArticle:
        restricted: webmaster
        controller: article:newArticle
        redirect: Login
        path: admin/ajouter-article

    AllUsers:
        restricted: admin
        controller: user:allUsers
        redirect: Login
        path: admin/utilisateurs
        params: 
            p: 
                type: int
                optional: true
            filter:
                type: int
                optional: true
            sort:
                type: int
                optional: true
            s:
                type: string
                optional: true

    AllUsersActions:
        restricted: admin
        controller: user:userActions
        path: admin/users-ajax
        params:
            action: 
                type: string
                optional: false

    AddUser:
        restricted: admin
        controller: user:addUser
        path: admin/ajouter-utilisateur
    
    EditUser:
        restricted: admin
        controller: user:editUser
        path: admin/modifier-utilisateur
        params:
            id:
                type: int
                optional: false


    DeleteUserFlag:
        restricted: admin
        controller: user:flagDeleteUser
        path: admin/supprimer-utilisateur
        params:
            id:
                type: int
                optional: false

    ViewUser:
        restricted: admin
        controller: user:viewUser
        path: admin/afficher-utilisateur
        params:
            id:
                type: int
                optional: false

    Categories:
        restricted: admin
        controller: category:allCategories
        path: admin/categories
        params: 
            p: 
                type: int
                optional: true 
            sort:
                type: sort
                optional: true

    DeleteCategory:
        restricted: admin
        controller: category:deleteCategory
        path: admin/supprimer-categorie
        params:
            id:
                type: int
                optional: false

    EditCategory:
        restricted: admin
        controller: category:editCategory
        path: admin/modifier-categorie
        params:
            id:
                type: int
                optional: false

    Tags:
        restricted: webmaster
        redirect: 
            guest: Admin
            permission: Login
        controller: category:allTags
        path: admin/tags
        params:
            p:
                type: int
                optional: true

    DeleteTag:
        restricted: moderator
        controller: category:deleteTag
        path: admin/supprimer-tag
        params:
            id:
                type: int
                optional: false

    EditTag:
        restricted: moderator
        controller: category:editTag
        path: admin/modifier-tag
        params:
            id:
                type: int
                optional: false

    Newsletter:
        restricted: webmaster
        controller: newsletter:allNewsletter
        path: admin/newsletter
        params:
            p:
                type: int
                optional: true
            sort:
                type: int
                optional: true
            filter:
                type: int
                optional: true

    AllArticles:
        restricted: webmaster
        controller: article:allArticles
        path: admin/articles
        params:
            filter:
                type: int
                optional: true
            p:
                type: int
                optional: true
            sort:
                type: int
                optional: true

    AllArticlesActions:
        restricted: webmaster
        controller: article:articleActions
        path: admin/articles-ajax
        params:
            action: 
                type: string
                optional: false

    EditArticle:
        restricted: webmaster
        controller: article:editArticle
        path: admin/modifier-article
        params:
            id: 
                type: int
                optional: false

    DeleteArticle:
        restricted: webmaster
        controller: article:deleteArticle
        path: admin/supprimer-article
        params:
            id: 
                type: int
                optional: false

    Stats:
        restricted: admin
        controller: stat:index
        path: admin/statistiques

    ExportStats:
        restricted: admin
        controler: stat:export
        path: admin/exporter-statistiques

    Medias:
        restricted: webmaster
        controller: media:allMedias
        path: admin/medias
        params:
            filter:
                type: int
                optional: true
            p:
                type: int
                optional: true

    MediaAjaxPagination:
        restricted: webmaster
        controller: media:modalPaginationAjax
        path: admin/media-modal-page-ajax
        params:
            p:
                type: int
                optional: false  

    EditMedia:
        restricted: webmaster
        controller: media:editMedia
        path: admin/modifier-media
        params:
            type:   
                type: int
                optional: true
            id: 
                type: int
                optional: true
   
    newMediaVideo:
        restricted: webmaster
        controller: media:newVideo
        path: admin/ajouter-video
        
    newMediaImage:
        restricted: webmaster
        controller: media:newImage
        path: admin/ajouter-image

    newMediaMusic:
        restricted: webmaster
        controller: media:newMusic
        path: admin/ajouter-musique

    DeleteMedia:
        restricted: webmaster
        controller: media:deleteMedia
        path: admin/supprimer-media
        params:
            id:
                type: int
                optional: false

    MediaAjaxPagination:
        restricted: webmaster
        controller: media:modalPaginationAjax
        path: admin/media-modal-page-ajax
        params:
            p:
                type: int
                optional: false    

    ImageAjaxPagination:
        restricted: webmaster
        controller: media:modalImagePaginationAjax
        path: admin/image-modal-page-ajax
        params:
            p:
                type: int
                optional: false

    Themes:
        restricted: admin
        controller: theme:index
        path: admin/themes

    MenuCreator:
        restricted: admin
        controller: theme:menuCreator
        path: admin/personnaliser-menu

    SaveMenu:
        restricted: admin
        controller: theme:saveMenu
        path: admin/save-menu-ajax

    SetTheme:
        restricted: admin
        controller: theme:setTheme
        path: admin/set-theme
        params:
            name:
                type: string
                optional: false

    Pages:
        restricted: webmaster
        controller: page:allPages
        path: admin/pages
        params:
            filter:
                type: int
                optional: true
            p:
                type: int
                optional: true
            sort:
                type: int
                optional: true

    NewPage:
        restricted: webmaster
        controller: page:newPage
        path: admin/ajouter-page

    EditPage:
        restricted: webmaster
        controller: page:editPage
        path: admin/modifier-page
        params:
            id:
                type: int
                optional: false

    DeletePage:
        restricted: webmaster
        controller: page:deletePage
        path: admin/supprimer-page
        params:
            id:
                type: int
                optional: false

    Comments:
        restricted: moderator
        controller: comment:allComments
        redirect: Login
        path: admin/commentaires
        params:
            filter:
                type: int
                optional: true
            p:
                type: int
                optional: true
            sort:
                type: int
                optional: true 

    AllCommentsActions:
        restricted: moderator
        controller: comment:commentActions
        redirect: Login
        path: admin/comments-ajax
        params:
            action:
                type: string
                optional: false

    ModerateComment:
        restricted: moderator
        controller: comment:singleComment
        path: admin/moderer-commentaire
        params:
            id:
                type: int
                optional: false

    DisapproveComment:
        restricted: moderator
        controller: comment:disapproveComment
        path: comment/disapprove
        redirect: Login
        params:
            id:
                type: int
                optional: false
            redirect:
                type: string
                optional: false

    ApproveComment:
        restricted: moderator
        controller: comment:approveComment
        path: comment/approve
        redirect: Login
        params:
            id:
                type: int
                optional: false
            redirect:
                type: string
                optional: false 

    DeleteComment:
        restricted: user
        controller: comment:deleteComment
        path: comment/delete
        params:
            id:
                type: int
                optional: false
            redirect:
                type: string
                optional: false 

    ReportComment:
        restricted: all
        controller: comment:reportComment
        path: comment/report
        params:
            id:
                type: int
                optional: false
            redirect:
                type: string
                optional: false


    generalSettings:
        restricted: admin
        redirect: Login
        controller: setting:index
        path: admin/parametres

    viewSettings:
        restricted: admin
        controller: setting:view
        path: admin/parametre-lecture

    postSettings:
        restricted: admin
        controller: setting:post        
        path: admin/parametre-publication    

    logoutEveryone:
        restricted: admin
        controller: setting:logoutEveryone
        path: admin/most-deadly-function

    Events:
        restricted: admin
        controller: event:allEvents
        path: admin/evenements
        params:
            filter:
                type: int
                optional: true
            p:
                type: int
                optional: true

    EditEvent:
        restricted: admin
        controller: event:editEvent
        path: admin/modifier-evenement
        params:
            id:
                type: int
                optional: false

    DeleteEvent:
        restricted: admin
        controller: event:deleteEvent
        path: admin/supprimer-evenement
        params:
            id:
                type: int
                optional: false

    AddEvent:
        restricted: webmaster
        controller: event:addEvent
        path: admin/ajouter-evenement

    getNewPassword:
        restricted: connected
        redirect: Admin
        controller: login:getNewPassword
        path: recuperer-compte

    forceNewPassword:
        restricted: admin
        controller: user:forceNewPassword
        path: admin/nouveau-mot-de-passe
        params:
            id:
                type: int
                optional: false

    disabledUser:
        restricted: admin
        controller: user:disableUser
        path: admin/desactiver-utilisateur

    banUser:
        restricted: admin
        controller: user:banUser
        path: admin/bannir-utilisateur

    destroyUser:
        restricted: admin
        controller: user:destroyUser
        path: admin/detruire-utilisateur
        params:
            id:
                type: int
                optional: false

    SignUpNewsletter:
        restricted: connected
        redirect: Admin
        controller: newsletter:signUp
        path: inscription-newsletter

    SignUpNewsletterSuccess:
        restricted: connected
        redirect: Admin
        controller: newsletter:success
        path: newsletter-merci 

    DevTest:
        restricted: all
        controller: admin:devTest
        path: admin/test

    DeleteFlashSessionAjax:
        restricted: webmaster
        controller: framework:deleteFlashSessionAjax
        path: admin/delete-flash-session-ajax    

    AddFlashSessionAjaxAction:
        restricted: webmaster
        controller: framework:addFlashSessionAjaxAction
        path: admin/add-flash-session-ajax
        params:
            type:
                type: string
                optional: false
            body:
                type: string
                optional: false
            title:
                type: string
                optional: false

    Rss:
        restricted: all
        controller: article:getRss
        path: rss    

    Sitemap:
        restricted: all
        controller: index:getSitemap
        path: sitemap

    DismissBlock:
        restricted: webmaster
        controller: framework:dismissBlock
        path: admin/block-dismiss
        params:
            type:
                type: string
                optional: false

    ResetDashboard:
        restricted: webmaster
        controller: framework:resetDashboard
        path: admin/reset-dashboard
        params:
            redirect:
                type: string
                optional: false    

    SaveOrderDashboard:
        restricted: webmaster
        controller: framework:dashboardOrder
        path: admin/dashboard-order
        params:
            left:
                type: string
                optional: false
            right:
                type: string
                optional: false
