routing:
    
    Index:
        restricted: all
        controller: index:index
        path: ""

    Error:
        restricted: all
        controller: error:notFound
        path: error

    Error404:
        restricted: all
        controller: error:notFound
        path: 404

    Error403:
        restricted: all
        controller: error:forbidden
        path: 403

    Admin:
        restricted: admin
        controller: admin:index
        path: admin

    Login:
        restricted: connected
        controller: login:index
        path: connexion

    Logout:
        restricted: all
        controller: login:logout
        path: logout

    Signup:
        restricted: connected
        controller: login:signup
        path: inscription


    Profile:
        restricted: user
        controller: user:index
        path: profil

    NewArticle:
        restricted: admin
        controller: article:newArticle
        path: admin/ajouter-article

    AllUsers:
        restricted: admin
        controller: user:allUsers
        path: admin/utilisateurs
        params: 
            p: 
                type: int
                optional: true
            filter:
                type: int
                optional: true
            sort:
                type: int
                optional: true

    AllUsersAjax:
        restricted: admin
        controller: user:allUsersAjax
        path: admin/utilisateurs-ajax

    AddUser:
        restricted: admin
        controller: user:addUser
        path: admin/ajouter-utilisateur
    
    EditUser:
        restricted: admin
        controller: user:editUser
        path: admin/modifier-utilisateur

    ViewUser:
        restricted: admin
        controller: user:viewUser
        path: admin/afficher-utilisateur

    Categories:
        restricted: admin
        controller: category:allCategories
        path: admin/categories

    Tags:
        restricted: admin
        controller: category:allTags
        path: admin/tags

    AllArticles:
        restricted: admin
        controller: article:allArticles
        path: admin/articles

    EditArticle:
        restricted: admin
        controller: admin:newArticle
        path: admin/modifier-article

    Medias:
        restricted: admin
        controller: media:index
        path: admin/medias

    EditTheme:
        restricted: admin
        controller: theme:editThemes
        path: admin/modifier-theme

    Themes:
        restricted: admin
        controller: theme:index
        path: admin/themes

    ThemeCreator:
        restricted: admin
        controller: theme:themeCreator
        path: admin/theme-creator

    Pages:
        restricted: admin
        controller: page:index
        path: admin/pages

    NewPage:
        restricted: admin
        controller: page:addPage
        path: admin/ajouter-page

    Comments:
        restricted: admin
        controller: comment:index
        path: admin/commentaires

    Parameters:
        restricted: admin
        controller: setting:index
        path: admin/parametres

    Events:
        restricted: admin
        controller: event:index
        path: admin/evenements

    AddEvent:
        restricted: admin
        controller: event:addEvent
        path: admin/ajouter-evenements

    getNewPassword:
        restricted: connected
        controller: login:getNewPassword
        path: recuperer-compte

    forceNewPassword:
        restricted: admin
        controller: user:forceNewPassword
        path: admin/nouveau-mot-de-passe

    disabledUser:
        restricted: admin
        controller: user:disableUser
        path: admin/desactiver-utilisateur

    banUser:
        restricted: admin
        controller: user:banUser
        path: admin/bannir-utilisateur

    deleteUser:
        restricted: admin
        controller: user:deleteUser
        path: admin/supprimer-utilisateur

    destroyUser:
        restricted: admin
        controller: user:deleteUser
        path: admin/detruire-utilisateur

    SignUpNewsletter:
        restricted: all
        controller: newsletter:signUp
        path: newsletter

    DevTest:
        restricted: all
        controller: admin:devTest
        path: admin/test

    DeleteFlashSessionAjax:
        restricted: all
        controller: framework:deleteFlashSessionAjax
        path: admin/delete-flash-session-ajax