routing:

    Index:
        restricted: all
        controller: index:index
        path: ""

    Error:
        restricted: all
        controller: error:notFound
        path: error/index

    Error404:
        restricted: all
        controller: error:notFound
        path: error/404

    Error403:
        restricted: all
        controller: error:forbidden
        path: error/403

    Admin:
        restricted: admin
        controller: admin:index
        path: admin

    Login:
        restricted: all
        controller: login:index
        path: login

    Logout:
        restricted: all
        controller: login:logout
        path: logout

    Signup:
        restricted: all
        controller: login:signup
        path: signup

    Update:
        restricted: admin
        controller: login:update
        path: admin/updateuser

    Profile:
        restricted: user
        controller: user:index
        path: admin/profile

    NewArticle:
        restricted: admin
        controller: admin:newArticle
        path: admin/ajouter-article

    AllUsers:
        restricted: admin
        controller: user:allUsers
        path: admin/users
        
    NewCategory:
        restricted: admin
        controller: admin:newCategory
        path: admin/ajouter-categorie

    AllArticles:
        restricted: admin
        controller: article:allArticles
        path: admin/articles

    EditArticle:
        restricted: admin
        controller: admin:newArticle
        path: admin/modifier-article