version: "2.0"
services:
    mariadb:
        image: mariadb
        container_name: wesic-mariadb
        environment:
         - MYSQL_ROOT_PASSWORD=mypass
        volumes:
         - ./mysql/DB:/var/lib/mysql
        ports:
         - 3306:3306
    php:
        build:
          context: ./
          dockerfile: Dockerfile
        volumes:
          - ../:/var/www/html/
          - ./php/apache2/apache2.conf:/etc/apache2/apache2.conf
        links:
         - mariadb:db
        ports:
          - "80:80"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wesic-phpmyadmin
        environment:
         - MYSQL_ROOT_PASSWORD=mypass
        ports:
         - "8082:80"
        links:
         - mariadb:db
